# Generated by Django 6.0 on 2025-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='estimated_hours',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
