# Generated by Django 5.2.5 on 2026-01-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quicknote_title_quicknote_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicknote',
            options={'ordering': ['-is_pinned', '-pinned_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='quicknote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quicknote',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
