# Generated by Django 5.2.5 on 2026-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_approved_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
