# Generated by Django 5.2.5 on 2026-01-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignment_description_assignment_priority_and_more'),
    ]

    operations = [
    ]
